"""QC generation for proxy models.

The proxy reuses the original skeleton verbatim, so `$includemodel` resolves
against the stock animation models and every animation is inherited. Hitboxes
and attachments are copied across so shooting and special-infected grabs keep
working against the simplified mesh.
"""

from __future__ import annotations

import math

import numpy as np

from . import smd
from .mdl import Mdl


def _fmt(value: float) -> str:
    return f"{value:.6f}".rstrip("0").rstrip(".") or "0"


def _vec(values) -> str:
    return " ".join(_fmt(float(v)) for v in values)


# studiohdr flags that have a direct QC equivalent, so the proxy keeps the
# same engine-side behaviour as the model it replaces.
FLAG_COMMANDS: tuple[tuple[int, str], ...] = (
    (0x00000004, "$opaque"),
    (0x00000008, "$mostlyopaque"),
    (0x00000800, "$noforcedfade"),
    (0x00010000, "$ambientboost"),
    (0x00020000, "$donotcastshadows"),
)


def include_path(stored: str) -> str:
    """`$includemodel` is relative to models/, but the MDL stores it prefixed."""
    rel = stored.replace("\\", "/").lstrip("/")
    if rel.lower().startswith("models/"):
        rel = rel[len("models/") :]
    return rel


def matrix_to_qangle(matrix: tuple[float, ...]) -> tuple[float, float, float]:
    """Invert Source's AngleMatrix to recover (pitch, yaw, roll) in degrees."""
    m = np.array(matrix, dtype=np.float64).reshape(3, 4)[:, :3]
    sp = -max(-1.0, min(1.0, float(m[2][0])))
    pitch = math.asin(sp)
    if abs(m[2][0]) < 0.9999995:
        yaw = math.atan2(float(m[1][0]), float(m[0][0]))
        roll = math.atan2(float(m[2][1]), float(m[2][2]))
    else:  # gimbal lock: yaw and roll are degenerate, fold them together
        yaw = math.atan2(-float(m[0][1]), float(m[1][1]))
        roll = 0.0
    return math.degrees(pitch), math.degrees(yaw), math.degrees(roll)


def build(
    model: Mdl,
    smd_name: str,
    material_dir: str,
    sequence_name: str = "cvmod_ref",
    define_bones: bool = False,
) -> str:
    lines: list[str] = [
        "// Generated by cvmod - proxy mesh built from the model's own hitboxes.",
        f"// Source: {model.path.name}",
        "",
        f'$modelname "{model.internal_name}"',
        f'$body "proxy" "{smd_name}"',
        f'$cdmaterials "{material_dir}"',
        f'$surfaceprop "{model.surfaceprop}"',
        '$contents "solid"',
        f"$eyeposition {_vec(model.eye_position)}",
        f"$bbox {_vec(model.hull_min)} {_vec(model.hull_max)}",
        f"$cbox {_vec(model.view_bbmin)} {_vec(model.view_bbmax)}",
        "$scale 1",
    ]
    # $illumposition is deliberately omitted: it only picks the lighting sample
    # point, which does nothing for unlit materials, and studiomdl rotates the
    # value it is given.
    lines.extend(cmd for bit, cmd in FLAG_COMMANDS if model.flags & bit)
    lines.append("")

    if define_bones:
        # Without this studiomdl collapses every bone the simplified mesh does
        # not weight (53 down to 23 on the Hunter), which would strip bones the
        # animations and game code rely on. Angles are QAngle in degrees here,
        # whereas the SMD skeleton uses QAngle in radians.
        for bone in model.bones:
            parent = model.bones[bone.parent].name if bone.parent >= 0 else ""
            rot_deg = [math.degrees(v) for v in smd.bone_qangle(bone)]
            lines.append(
                f'$definebone "{bone.name}" "{parent}" '
                f"{_vec(bone.pos)} {_vec(rot_deg)} 0 0 0 0 0 0"
            )
        lines.append("")

    seen: set[str] = set()
    for att in model.attachments:
        if not att.name or att.name.lower() in seen:
            continue  # a few models declare the same attachment twice
        seen.add(att.name.lower())
        m = np.array(att.matrix, dtype=np.float64).reshape(3, 4)
        offset = (m[0][3], m[1][3], m[2][3])
        angles = matrix_to_qangle(att.matrix)
        lines.append(
            f'$attachment "{att.name}" "{model.bone_name(att.bone)}" '
            f"{_vec(offset)} rotate {_vec(angles)}"
        )
    if seen:
        lines.append("")

    for hbset in model.hitbox_sets:
        lines.append(f'$hboxset "{hbset.name}"')
        for box in hbset.boxes:
            lines.append(
                f'$hbox {box.group} "{model.bone_name(box.bone)}" '
                f"{_vec(box.bbmin)} {_vec(box.bbmax)}"
            )
        lines.append("")

    lines.append(f'$sequence "{sequence_name}" "{smd_name}" fps 30 loop')
    lines.append("")
    for include in model.include_models:
        lines.append(f'$includemodel "{include_path(include)}"')
    lines.append("")
    return "\n".join(lines)
